Document: phreebird-dnssec
Title: Debian phreebird-dnssec Manual
Author: <insert document author here>
Abstract: This manual describes what phreebird-dnssec is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/phreebird-dnssec/phreebird-dnssec.sgml.gz

Format: postscript
Files: /usr/share/doc/phreebird-dnssec/phreebird-dnssec.ps.gz

Format: text
Files: /usr/share/doc/phreebird-dnssec/phreebird-dnssec.text.gz

Format: HTML
Index: /usr/share/doc/phreebird-dnssec/html/index.html
Files: /usr/share/doc/phreebird-dnssec/html/*.html
